import { Link } from "react-router-dom";
import { Badge, Panel } from "../../components/Common";

export default function ComputerGraphicsMethodology() {
  return (
    <div>
      <Panel title="Computer Graphics Methodology">
        <p style={{ fontSize: 12, color: "var(--text-mid)" }}>
          TreasuryX's Computer Graphics work powers one real product capability:{" "}
          <Link to="/visualization/3d-market">3D Market</Link> — interactive 3D rendering of the yield curve, FX
          volatility, and portfolio stress surfaces, all built from live Treasury data. The rendering pipeline
          documented below runs inside that production page (open "Graphics Details" and "Explain This
          Visualization" there for the live version), not a separate lab.
        </p>
      </Panel>

      <Panel title="Rendering Pipeline (as used in 3D Market)">
        <table className="data-table">
          <tbody>
            <tr><td style={{ textAlign: "left", width: 180 }}>Geometry</td><td style={{ textAlign: "left" }}>Custom THREE.BufferGeometry, built per-frame-data from a position/color/index buffer — a triangulated grid mesh, not a canned chart primitive</td></tr>
            <tr><td style={{ textAlign: "left" }}>Model transform</td><td style={{ textAlign: "left" }}>Data values mapped to object space (x = category index, y = normalized magnitude, z = second category index)</td></tr>
            <tr><td style={{ textAlign: "left" }}>View transform</td><td style={{ textAlign: "left" }}>OrbitControls maintains camera position/target; Three.js derives the view (look-at) matrix every frame</td></tr>
            <tr><td style={{ textAlign: "left" }}>Projection</td><td style={{ textAlign: "left" }}>Switchable perspective (45° FOV) or orthographic — both real, live in the production page</td></tr>
            <tr><td style={{ textAlign: "left" }}>Depth</td><td style={{ textAlign: "left" }}>WebGL's default depth buffer (z-buffer) resolves surface/wireframe/marker occlusion</td></tr>
            <tr><td style={{ textAlign: "left" }}>Lighting / shading</td><td style={{ textAlign: "left" }}>Ambient + 2 directional lights; standard PBR-lite material in "Market View", or the custom shader's own diffuse term in "Risk View"</td></tr>
            <tr><td style={{ textAlign: "left" }}>Shader</td><td style={{ textAlign: "left" }}>A hand-written vertex + fragment GLSL shader (THREE.ShaderMaterial, not a material-property tweak) computes per-pixel color from data height vs. an interactive threshold uniform, blended with a diffuse lighting term</td></tr>
            <tr><td style={{ textAlign: "left" }}>Interaction</td><td style={{ textAlign: "left" }}>Raycasting against per-vertex marker meshes for hover tooltips; OrbitControls for rotate/zoom/pan</td></tr>
            <tr><td style={{ textAlign: "left" }}>Coordinate system</td><td style={{ textAlign: "left" }}>Right-handed, Y-up (Three.js default)</td></tr>
          </tbody>
        </table>
      </Panel>

      <Panel title="Finance → Graphics integration">
        <p style={{ fontSize: 11.5, color: "var(--text-mid)" }}>
          The 3D Portfolio Stress Surface is generated by calling the real scenario engine over a grid of FX/yield
          shocks against the currently open positions — including any value corrected via{" "}
          <Link to="/intelligence/financial-image">Financial Image Intelligence</Link>. Committing a CV-extracted
          bond yield changes the bond's price/DV01 everywhere (Rates & Bonds, Risk, Scenario) and the 3D surfaces
          that read through the same effective-market-view layer. Nothing in the 3D views is hard-coded.
        </p>
        <Badge kind="info">See ACADEMIC_MAPPING.md / Course Mapping for the full syllabus cross-reference</Badge>
      </Panel>

      <Panel title="What has no natural Treasury production use (kept as supplementary evidence)">
        <p style={{ fontSize: 11.5, color: "var(--text-mid)" }}>
          DDA/Bresenham/Midpoint-Circle rasterization, 2D homogeneous-coordinate transforms and line clipping, and
          VR/AR/XR concepts don't have a sensible place inside a Treasury workflow — forcing them in would hurt the
          product, not help it. Per the project's own design rule, they're implemented and documented as direct
          syllabus evidence instead: see{" "}
          <Link to="/evidence/graphics/raster">Raster Graphics</Link>,{" "}
          <Link to="/evidence/graphics/transform2d">2D Transformations & Clipping</Link>, and{" "}
          <Link to="/evidence/graphics/vr-ar">VR/AR Concepts</Link>.
        </p>
      </Panel>

      <Panel title="Unity — explicitly not implemented">
        <p style={{ fontSize: 11.5, color: "var(--text-mid)" }}>
          The syllabus's Unity-based interactive 3D scene lab is not implemented — Unity is a standalone desktop
          game engine outside this web application's stack. The equivalent underlying concepts (transformations,
          camera, projection, lighting, interaction) are covered by the WebGL/Three.js production 3D Market page
          instead.
        </p>
      </Panel>
    </div>
  );
}
